### ISSUE TITLE
PersistentMap does not support array as value.

### ISSUE THREAD

**Issue by bowenwang1996** [nearprotocol/near-runtime-ts#100]
PersistentMap cannot have something of array type as value due to lack of serialization support. Example https://studio.nearprotocol.com/?f=6k84p8jm3

**Comment by willemneal** [comment]
Found the issue.  The runtime should use the generic `encode/decode` methods on generic types since `[].serialize()` isn't a method.  The set method in the storage class used the serialized method.  I'll add a test and make a PR.

Here is an example of it working for the newest NEAR Studio and the most up to date binding code.

**Comment by willemneal** [comment]
fixed by #96
